AllCops:
  Exclude:
    - 'config/application.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
