default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fishcards_development
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: fishcards_test

production:
  <<: *default
  database: fishcards_production
  username: fishcards
  password: <%= ENV['FISHCARDS_DATABASE_PASSWORD'] %>
